import Flynn
import Foundation
import Socket
import PicaroonFramework
import Pamphlet

class GameService: RemoteActor {
    static let serviceName = "LD47_GAME_SERVICE"

    private var game = Game()

    override func safeInit() {
        game = Game(42)
    }

    private func _bePlayerJoin(_ playerID: String, _ playerName: String) -> String {
        if let json = try? game.addPlayer(playerID, playerName).json() {
            return json
        }
        return ""
    }

    private func _beGetBoard(_ playerID: String) -> String {
        if let json = try? game.getBoardUpdate(playerID).json() {
            return json
        }
        return ""
    }
}

// MARK: - Autogenerated by FlynnLint
// Contents of file after this marker will be overwritten as needed

extension GameService {

    struct BePlayerJoinCodableResponse: Codable {
        let response: String
    }
    struct BePlayerJoinCodableRequest: Codable {
        let arg0: String
        let arg1: String
    }
    struct BeGetBoardCodableResponse: Codable {
        let response: String
    }
    struct BeGetBoardCodableRequest: Codable {
        let arg0: String
    }

    @discardableResult
    public func bePlayerJoin(_ playerID: String,
                             _ playerName: String,
                             _ sender: Actor,
                             _ callback: @escaping (String) -> Void ) -> Self {
        let msg = BePlayerJoinCodableRequest(arg0: playerID, arg1: playerName)
        // swiftlint:disable:next force_try
        let data = try! JSONEncoder().encode(msg)
        unsafeSendToRemote("GameService", "bePlayerJoin", data, sender) {
            callback(
                // swiftlint:disable:next force_try
                (try! JSONDecoder().decode(BePlayerJoinCodableResponse.self, from: $0).response)
            )
        }
        return self
    }
    @discardableResult
    public func beGetBoard(_ playerID: String,
                           _ sender: Actor,
                           _ callback: @escaping (String) -> Void ) -> Self {
        let msg = BeGetBoardCodableRequest(arg0: playerID)
        // swiftlint:disable:next force_try
        let data = try! JSONEncoder().encode(msg)
        unsafeSendToRemote("GameService", "beGetBoard", data, sender) {
            callback(
                // swiftlint:disable:next force_try
                (try! JSONDecoder().decode(BeGetBoardCodableResponse.self, from: $0).response)
            )
        }
        return self
    }

    public func unsafeRegisterAllBehaviors() {
        safeRegisterRemoteBehavior("bePlayerJoin") { [unowned self] (data) in
            // swiftlint:disable:next force_try
            let msg = try! JSONDecoder().decode(BePlayerJoinCodableRequest.self, from: data)
            // swiftlint:disable:next force_try
            return try! JSONEncoder().encode(
                BePlayerJoinCodableResponse(response: self._bePlayerJoin(msg.arg0, msg.arg1)))
        }
        safeRegisterRemoteBehavior("beGetBoard") { [unowned self] (data) in
            // swiftlint:disable:next force_try
            let msg = try! JSONDecoder().decode(BeGetBoardCodableRequest.self, from: data)
            // swiftlint:disable:next force_try
            return try! JSONEncoder().encode(
                BeGetBoardCodableResponse(response: self._beGetBoard(msg.arg0)))
        }
    }
}
